name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn install

      - name: Compile and push to ecr
        run: mvn compile jib:build -Dimage=918030663991.dkr.ecr.us-east-1.amazonaws.com/mytestimage
      
