name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - name: Setup JDK
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        run: java -version

    - name: Build with Maven
      run: ./mvnw install -UskipTests

    - name: Compile and push to ecr
      run: ./mnvw compile jib:build -Dimage=918030663991.dkr.ecr.us-east-1.amazonaws.com/mytestimage
      
